### PR TITLE
Use os.IsTimeout instead of os.ErrDeadlineExceeded

### LINKED ISSUE #360: No longer compiles with Go 1.13
Ice no longer compiles with Go 1.13.  This is important for Galène, since some distributions still use 1.13.

```
$ /usr/lib/go-1.13/bin/go test ./...
# github.com/pion/ice/v2
../../../../pkg/mod/github.com/pion/ice/v2@v2.1.4/udp_mux.go:216:22: undefined: os.ErrDeadlineExceeded
```

### PR DESCRIPTION
**Pull request by jech**
This fixes compilation with Go 1.13 and 1.14.

Fixes #360.

### CODE REVIEW

**Review by davidzhao — APPROVED** [review]
sorry about the breakage. this looks good
