### ISSUE TITLE
No longer compiles with Go 1.13

### ISSUE THREAD

**Issue by jech** [pion/ice#360]
Ice no longer compiles with Go 1.13.  This is important for Galène, since some distributions still use 1.13.

```
$ /usr/lib/go-1.13/bin/go test ./...
# github.com/pion/ice/v2
../../../../pkg/mod/github.com/pion/ice/v2@v2.1.4/udp_mux.go:216:22: undefined: os.ErrDeadlineExceeded
```
